
services:
  quantum-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - ENV=${ENV}
    restart: always
    volumes:
      - .:/app
    depends_on:
      - quantum-db
    networks:
      - quantum-net

  quantum-db:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - quantum-db-data:/data/db
    command: ["--auth"]
    networks:
      - quantum-net

networks:
  quantum-net:
    driver: bridge

volumes:
  quantum-db-data: